/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/jobs": {
    /** Search for a job by using either a zipcode, string query and/or filters */
    get: {
      parameters: {
        query: {
          /** job search string */
          q?: string;
          /** postal code */
          pc?: string;
          /** hits per page */
          perpage?: number | null;
          /** page number */
          pagenum?: number | null;
          /** filter object as querystring, use post schema as example */
          f?: unknown[];
          /** return aggregated results */
          aggs?: boolean;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
    /** Search for a job by using either a zipcode, string query and filters */
    post: {
      parameters: {
        body: {
          body?: {
            /** @description query */
            q?: string | null;
            /**
             * @description show internal jobs
             * @default false
             */
            internal?: boolean | null;
            /** @description postalcode */
            pc?: string | null;
            /**
             * @description Use title, slug, updated, created, inserted or published
             * @default title.asc
             */
            sortby?: string | null;
            /**
             * @description hits per page
             * @default 10
             */
            perpage?: number | null;
            /**
             * @description page number
             * @default 1
             */
            pagenum?: number | null;
            /** @description filter */
            f?: {
              /**
               * @description category
               * @default
               */
              c?: string[] | null;
              /**
               * @description sector
               * @default
               */
              s?: string[] | null;
              /**
               * @description province
               * @default
               */
              p?: string[] | null;
              /**
               * @description shift work
               * @default
               */
              sw?: string[] | null;
              /**
               * @description education level
               * @default
               */
              el?: string[] | null;
              /**
               * @description account number
               * @default
               */
              an?: number[] | null;
              /**
               * @description branch name lowercase
               * @default
               */
              bn?: string[] | null;
            };
            /**
             * @description query type
             * @default 2
             */
            qtype?: number | null;
            /**
             * @description Show suggestions
             * @default true
             */
            sugs?: boolean | null;
            /** @description enable aggregation results */
            aggs?: boolean | null;
            /** @description add missing aggregations */
            missing_aggs?: boolean | null;
            /** @description show highlighted jobs */
            highlight?: boolean | null;
          };
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/{sortby}": {
    /** retrieve jobs and define sorting */
    get: {
      parameters: {
        path: {
          /** must contain title, slug, updated, created or published */
          sortby: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/{sortby}/{pagenum}": {
    /** retrieve jobs, define sorting and pagenum */
    get: {
      parameters: {
        path: {
          /** must contain title, slug, updated, created or published */
          sortby: string;
          /** page number must be > 0 */
          pagenum: number;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/{sortby}/{pagenum}/{perpage}": {
    /** retrieve jobs, define sorting, pagenum and amount per page */
    get: {
      parameters: {
        path: {
          /** must contain title, slug, updated, created or published */
          sortby: string;
          /** page number must be > 0 */
          pagenum: number;
          /** page number must be > 0 */
          perpage: number;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/{sortby}/{pagenum}/{perpage}/{jobid}": {
    /** retrieve jobs, define sorting, pagenum, amount per page by related jobid? */
    get: {
      parameters: {
        path: {
          /** must contain title, slug, updated, created or published */
          sortby: string;
          /** page number must be > 0 */
          pagenum: number;
          /** page number must be > 0 */
          perpage: number;
          /** jobid */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/total": {
    /** retrieve total number of published jobs */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/total/bylabel/{label}": {
    /** retrieve total jobs by label */
    get: {
      parameters: {
        path: {
          /** e.g. "top" */
          label: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/jobs/bylabel/{label}/{count}": {
    /** retrieve jobs by label and define result count */
    get: {
      parameters: {
        path: {
          /** label */
          label: string;
          /** result count must be > 0 */
          count: number;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/job/{jobid}": {
    /** retrieve job using jobid */
    get: {
      parameters: {
        path: {
          /** job id */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/job/old/{jobid}": {
    /** retrieve old job using jobid */
    get: {
      parameters: {
        path: {
          /** job id */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/job/related/{jobid}": {
    /** retrieve related jobs using jobid */
    get: {
      parameters: {
        path: {
          /** job id */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/job/related/{jobid}/{count}": {
    /** retrieve related job using jobid and set amount of items to retrieve */
    get: {
      parameters: {
        path: {
          /** job id */
          jobid: string;
          /** result count must be > 0 */
          count: number;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/customer/{account}/job/{jobid}": {
    /** lookup jobs from customer by account id? */
    get: {
      parameters: {
        path: {
          /** account */
          account: string;
          /** jobid */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/campaign/{jobid}": {
    /** get campaign jobid? */
    get: {
      parameters: {
        path: {
          /** jobid */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/campaign/old/{jobid}": {
    /** get old campaign jobid? */
    get: {
      parameters: {
        path: {
          /** jobid */
          jobid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/branches": {
    /** retrieve branches */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/branch/{id}": {
    /** retrieve branche by id */
    get: {
      parameters: {
        path: {
          /** search term, not functional will always return all branches */
          id: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/acmanagers": {
    /** retrieve all account managers */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/acmanagers/{branch}": {
    /** retrieve account managers by branch key (case sensitive) */
    get: {
      parameters: {
        path: {
          /** branch key */
          branch: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/autocomplete/{term}": {
    /** autocomplete search term */
    get: {
      parameters: {
        path: {
          /** search term */
          term: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/autocomplete/job/{term}": {
    /** autocomplete job search term */
    get: {
      parameters: {
        path: {
          /** job search term */
          term: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/check/postcode/{pc}": {
    /** check postcode */
    get: {
      parameters: {
        path: {
          /** postcode to test for validity, seems to not work on backend api, postalcode should be provided without a space e.g. 1011AA */
          pc: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/slug2id/job/{slug}": {
    /** Convert slug to id */
    get: {
      parameters: {
        path: {
          /** slug */
          slug: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/slug2id/campaign/{slug}": {
    /** Convert campaign slug to id */
    get: {
      parameters: {
        path: {
          /** slug */
          slug: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/sf2id/job/{sfid}": {
    /** Convert sfid to id */
    get: {
      parameters: {
        path: {
          /** sfid */
          sfid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/sf2id/campaign/{sfid}": {
    /** Convert campaign sfid to id */
    get: {
      parameters: {
        path: {
          /** sfid */
          sfid: string;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/xml": {
    /**
     * Retrieve job feed as xml, can be given 'nl' and 'be' query params which must be set to 1.
     *           Will return an XML with only the dutch vacancies by default, but can also return only the belgian vacancies
     *           or a merged XML of both based on the query params.
     */
    get: {
      parameters: {
        query: {
          nl?: number;
          be?: number;
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/campagnes/xml": {
    /** Retrieve campaign feed as xml */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/json": {
    /** Retrieve job feed as json */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/campagnes/json": {
    /** Retrieve job feed as json */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/csv": {
    /** Retrieve job feed as json */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/campagnes/csv": {
    /** Retrieve job feed as json */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/rp/xml": {
    /** Retrieve job feed as xml */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/rp/json": {
    /** Retrieve job feed as json */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/rp/csv": {
    /** Retrieve job feed as json */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/adwords": {
    /** Retrieve adwords feed as csv */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/indeed": {
    /** Retrieve indeed feed as csv */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/sitemap": {
    /** Retrieve sitemap xml */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
  "/feed/sitemap/jobs": {
    /** Retrieve jobs sitemap xml */
    get: {
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
}

export interface definitions {}

export interface operations {}

export interface external {}
