import animate from "tailwindcss-animate"; // https://github.com/jamiebuilds/tailwindcss-animate
import plugin from "tailwindcss/plugin";

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],

    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                xs: "384px",
                sm: "640px",
                md: "768px",
                lg: "1024px",
                xl: "1280px",
                "2xl": "1400px",
            },
        },
        maskImage: {
            "radial-gradient": "radial-gradient(50% 50% at 50% 50%, #000 0%, rgba(0, 0, 0, 0.00) 100%)",
        },
        maskMode: {
            alpha: "alpha",
            luminance: "luminance",
            "match-source": "match-source",
        },

        extend: {
            fontFamily: {
                sans: [
                    "InterVariable",
                    "Inter",
                    "apple-system",
                    "BlinkMacSystemFont",
                    "Segoe UI",
                    "Roboto",
                    "Oxygen-Sans",
                    "Ubuntu",
                    "Cantarell",
                    "Helvetica Neue",
                    "sans-serif",
                ],
            },
            fontSize: {
                xs: ["0.75rem", { lineHeight: "1.125rem" }],
                sm: ["0.875rem", { lineHeight: "1.25rem" }],
                md: ["1rem", { lineHeight: "1.5rem" }],
                lg: ["1.125rem", { lineHeight: "1.75rem" }],
                xl: ["1.25rem", { lineHeight: "1.865rem" }],
                "display-xs": ["1.5rem", { lineHeight: "2rem" }],
                "display-sm": ["1.875rem", { lineHeight: "2.375rem" }],
                "display-md": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em" }],
                "display-lg": ["3rem", { lineHeight: "3.75rem", letterSpacing: "-0.02em" }],
                "display-xl": ["3.75rem", { lineHeight: "4.5rem", letterSpacing: "-0.02em" }],
                "display-2xl": ["4.5rem", { lineHeight: "5.625rem", letterSpacing: "-0.02em" }],
            },
            spacing: {
                4.5: "1.125rem",
                5.5: "1.375rem",
                13: "3.25rem",
                15: "3.75rem",
                70: "17.5rem",
                84: "21rem",
            },
            boxShadow: {
                xs: "0px 1px 2px 0px rgba(16,24,40,0.05)",
                sm: "0px 1px 2px 0px rgba(16,24,40,0.06), 0px 1px 3px 0px rgba(16,24,40,0.1)",
                DEFAULT: "0px 2px 4px -2px rgba(16,24,40,0.06), 0px 4px 8px -2px rgba(16,24,40,0.1)",
                md: "0px 2px 4px -2px rgba(16,24,40,0.06), 0px 4px 8px -2px rgba(16,24,40,0.1)",
                lg: "0px 4px 6px -2px rgba(16,24,40,0.03), 0px 12px 16px -4px rgba(16,24,40,0.08)",
                xl: "0px 8px 8px -4px rgba(16,24,40,0.03), 0px 20px 24px -4px rgba(16,24,40,0.08)",
                "2xl": "0px 24px 48px -12px rgba(16,24,40,0.18)",
                "3xl": "0px 32px 64px -12px rgba(16,24,40,0.14)",
            },
            backgroundImage: {
                "mask-radial-gradient": "radial-gradient(50% 50% at 50% 50%, #000 0%, rgba(0, 0, 0, 0.00) 100%)",
            },
            opacity: {},
            colors: {
                white: "hsl(var(--base-white) / <alpha-value>)",
                black: "hsl(var(--base-black) / <alpha-value>)",
                transparent: "hsl(var(--base-transparent) / <alpha-value>)",
                gray: {
                    25: "hsl(var(--gray-25) / <alpha-value>)",
                    50: "hsl(var(--gray-50) / <alpha-value>)",
                    100: "hsl(var(--gray-100) / <alpha-value>)",
                    200: "hsl(var(--gray-200) / <alpha-value>)",
                    300: "hsl(var(--gray-300) / <alpha-value>)",
                    400: "hsl(var(--gray-400) / <alpha-value>)",
                    500: "hsl(var(--gray-500) / <alpha-value>)",
                    600: "hsl(var(--gray-600) / <alpha-value>)",
                    700: "hsl(var(--gray-700) / <alpha-value>)",
                    800: "hsl(var(--gray-800) / <alpha-value>)",
                    900: "hsl(var(--gray-900) / <alpha-value>)",
                    950: "hsl(var(--gray-950) / <alpha-value>)",
                },
                "gray-dark": {
                    25: "hsl(var(--gray-dark-25) / <alpha-value>)",
                    50: "hsl(var(--gray-dark-50) / <alpha-value>)",
                    100: "hsl(var(--gray-dark-100) / <alpha-value>)",
                    200: "hsl(var(--gray-dark-200) / <alpha-value>)",
                    300: "hsl(var(--gray-dark-300) / <alpha-value>)",
                    400: "hsl(var(--gray-dark-400) / <alpha-value>)",
                    500: "hsl(var(--gray-dark-500) / <alpha-value>)",
                    600: "hsl(var(--gray-dark-600) / <alpha-value>)",
                    700: "hsl(var(--gray-dark-700) / <alpha-value>)",
                    800: "hsl(var(--gray-dark-800) / <alpha-value>)",
                    900: "hsl(var(--gray-dark-900) / <alpha-value>)",
                    950: "hsl(var(--gray-dark-950) / <alpha-value>)",
                },
                brand: {
                    25: "hsl(var(--brand-25) / <alpha-value>)",
                    50: "hsl(var(--brand-50) / <alpha-value>)",
                    100: "hsl(var(--brand-100) / <alpha-value>)",
                    200: "hsl(var(--brand-200) / <alpha-value>)",
                    300: "hsl(var(--brand-300) / <alpha-value>)",
                    400: "hsl(var(--brand-400) / <alpha-value>)",
                    500: "hsl(var(--brand-500) / <alpha-value>)",
                    600: "hsl(var(--brand-600) / <alpha-value>)",
                    700: "hsl(var(--brand-700) / <alpha-value>)",
                    800: "hsl(var(--brand-800) / <alpha-value>)",
                    900: "hsl(var(--brand-900) / <alpha-value>)",
                    950: "hsl(var(--brand-950) / <alpha-value>)",
                },
                error: {
                    25: "hsl(var(--error-25) / <alpha-value>)",
                    50: "hsl(var(--error-50) / <alpha-value>)",
                    100: "hsl(var(--error-100) / <alpha-value>)",
                    200: "hsl(var(--error-200) / <alpha-value>)",
                    300: "hsl(var(--error-300) / <alpha-value>)",
                    400: "hsl(var(--error-400) / <alpha-value>)",
                    500: "hsl(var(--error-500) / <alpha-value>)",
                    600: "hsl(var(--error-600) / <alpha-value>)",
                    700: "hsl(var(--error-700) / <alpha-value>)",
                    800: "hsl(var(--error-800) / <alpha-value>)",
                    900: "hsl(var(--error-900) / <alpha-value>)",
                    950: "hsl(var(--error-950) / <alpha-value>)",
                },
                warning: {
                    25: "hsl(var(--warning-25) / <alpha-value>)",
                    50: "hsl(var(--warning-50) / <alpha-value>)",
                    100: "hsl(var(--warning-100) / <alpha-value>)",
                    200: "hsl(var(--warning-200) / <alpha-value>)",
                    300: "hsl(var(--warning-300) / <alpha-value>)",
                    400: "hsl(var(--warning-400) / <alpha-value>)",
                    500: "hsl(var(--warning-500) / <alpha-value>)",
                    600: "hsl(var(--warning-600) / <alpha-value>)",
                    700: "hsl(var(--warning-700) / <alpha-value>)",
                    800: "hsl(var(--warning-800) / <alpha-value>)",
                    900: "hsl(var(--warning-900) / <alpha-value>)",
                    950: "hsl(var(--warning-950) / <alpha-value>)",
                },
                success: {
                    25: "hsl(var(--success-25) / <alpha-value>)",
                    50: "hsl(var(--success-50) / <alpha-value>)",
                    100: "hsl(var(--success-100) / <alpha-value>)",
                    200: "hsl(var(--success-200) / <alpha-value>)",
                    300: "hsl(var(--success-300) / <alpha-value>)",
                    400: "hsl(var(--success-400) / <alpha-value>)",
                    500: "hsl(var(--success-500) / <alpha-value>)",
                    600: "hsl(var(--success-600) / <alpha-value>)",
                    700: "hsl(var(--success-700) / <alpha-value>)",
                    800: "hsl(var(--success-800) / <alpha-value>)",
                    900: "hsl(var(--success-900) / <alpha-value>)",
                    950: "hsl(var(--success-950) / <alpha-value>)",
                },
                info: {
                    25: "hsl(var(--info-25) / <alpha-value>)",
                    50: "hsl(var(--info-50) / <alpha-value>)",
                    100: "hsl(var(--info-100) / <alpha-value>)",
                    200: "hsl(var(--info-200) / <alpha-value>)",
                    300: "hsl(var(--info-300) / <alpha-value>)",
                    400: "hsl(var(--info-400) / <alpha-value>)",
                    500: "hsl(var(--info-500) / <alpha-value>)",
                    600: "hsl(var(--info-600) / <alpha-value>)",
                    700: "hsl(var(--info-700) / <alpha-value>)",
                    800: "hsl(var(--info-800) / <alpha-value>)",
                    900: "hsl(var(--info-900) / <alpha-value>)",
                    950: "hsl(var(--info-950) / <alpha-value>)",
                },
                help: {
                    25: "hsl(var(--help-25) / <alpha-value>)",
                    50: "hsl(var(--help-50) / <alpha-value>)",
                    100: "hsl(var(--help-100) / <alpha-value>)",
                    200: "hsl(var(--help-200) / <alpha-value>)",
                    300: "hsl(var(--help-300) / <alpha-value>)",
                    400: "hsl(var(--help-400) / <alpha-value>)",
                    500: "hsl(var(--help-500) / <alpha-value>)",
                    600: "hsl(var(--help-600) / <alpha-value>)",
                    700: "hsl(var(--help-700) / <alpha-value>)",
                    800: "hsl(var(--help-800) / <alpha-value>)",
                    900: "hsl(var(--help-900) / <alpha-value>)",
                    950: "hsl(var(--help-950) / <alpha-value>)",
                },
                "gray-blue": {
                    25: "hsl(var(--gray-blue-25) / <alpha-value>)",
                    50: "hsl(var(--gray-blue-50) / <alpha-value>)",
                    100: "hsl(var(--gray-blue-100) / <alpha-value>)",
                    200: "hsl(var(--gray-blue-200) / <alpha-value>)",
                    300: "hsl(var(--gray-blue-300) / <alpha-value>)",
                    400: "hsl(var(--gray-blue-400) / <alpha-value>)",
                    500: "hsl(var(--gray-blue-500) / <alpha-value>)",
                    600: "hsl(var(--gray-blue-600) / <alpha-value>)",
                    700: "hsl(var(--gray-blue-700) / <alpha-value>)",
                    800: "hsl(var(--gray-blue-800) / <alpha-value>)",
                    900: "hsl(var(--gray-blue-900) / <alpha-value>)",
                    950: "hsl(var(--gray-blue-950) / <alpha-value>)",
                },
                "gray-cool": {
                    25: "hsl(var(--gray-cool-25) / <alpha-value>)",
                    50: "hsl(var(--gray-cool-50) / <alpha-value>)",
                    100: "hsl(var(--gray-cool-100) / <alpha-value>)",
                    200: "hsl(var(--gray-cool-200) / <alpha-value>)",
                    300: "hsl(var(--gray-cool-300) / <alpha-value>)",
                    400: "hsl(var(--gray-cool-400) / <alpha-value>)",
                    500: "hsl(var(--gray-cool-500) / <alpha-value>)",
                    600: "hsl(var(--gray-cool-600) / <alpha-value>)",
                    700: "hsl(var(--gray-cool-700) / <alpha-value>)",
                    800: "hsl(var(--gray-cool-800) / <alpha-value>)",
                    900: "hsl(var(--gray-cool-900) / <alpha-value>)",
                    950: "hsl(var(--gray-cool-950) / <alpha-value>)",
                },
                "gray-modern": {
                    25: "hsl(var(--gray-modern-25) / <alpha-value>)",
                    50: "hsl(var(--gray-modern-50) / <alpha-value>)",
                    100: "hsl(var(--gray-modern-100) / <alpha-value>)",
                    200: "hsl(var(--gray-modern-200) / <alpha-value>)",
                    300: "hsl(var(--gray-modern-300) / <alpha-value>)",
                    400: "hsl(var(--gray-modern-400) / <alpha-value>)",
                    500: "hsl(var(--gray-modern-500) / <alpha-value>)",
                    600: "hsl(var(--gray-modern-600) / <alpha-value>)",
                    700: "hsl(var(--gray-modern-700) / <alpha-value>)",
                    800: "hsl(var(--gray-modern-800) / <alpha-value>)",
                    900: "hsl(var(--gray-modern-900) / <alpha-value>)",
                    950: "hsl(var(--gray-modern-950) / <alpha-value>)",
                },
                "gray-neutral": {
                    25: "hsl(var(--gray-neutral-25) / <alpha-value>)",
                    50: "hsl(var(--gray-neutral-50) / <alpha-value>)",
                    100: "hsl(var(--gray-neutral-100) / <alpha-value>)",
                    200: "hsl(var(--gray-neutral-200) / <alpha-value>)",
                    300: "hsl(var(--gray-neutral-300) / <alpha-value>)",
                    400: "hsl(var(--gray-neutral-400) / <alpha-value>)",
                    500: "hsl(var(--gray-neutral-500) / <alpha-value>)",
                    600: "hsl(var(--gray-neutral-600) / <alpha-value>)",
                    700: "hsl(var(--gray-neutral-700) / <alpha-value>)",
                    800: "hsl(var(--gray-neutral-800) / <alpha-value>)",
                    900: "hsl(var(--gray-neutral-900) / <alpha-value>)",
                    950: "hsl(var(--gray-neutral-950) / <alpha-value>)",
                },
                "gray-iron": {
                    25: "hsl(var(--gray-iron-25) / <alpha-value>)",
                    50: "hsl(var(--gray-iron-50) / <alpha-value>)",
                    100: "hsl(var(--gray-iron-100) / <alpha-value>)",
                    200: "hsl(var(--gray-iron-200) / <alpha-value>)",
                    300: "hsl(var(--gray-iron-300) / <alpha-value>)",
                    400: "hsl(var(--gray-iron-400) / <alpha-value>)",
                    500: "hsl(var(--gray-iron-500) / <alpha-value>)",
                    600: "hsl(var(--gray-iron-600) / <alpha-value>)",
                    700: "hsl(var(--gray-iron-700) / <alpha-value>)",
                    800: "hsl(var(--gray-iron-800) / <alpha-value>)",
                    900: "hsl(var(--gray-iron-900) / <alpha-value>)",
                    950: "hsl(var(--gray-iron-950) / <alpha-value>)",
                },
                "gray-true": {
                    25: "hsl(var(--gray-true-25) / <alpha-value>)",
                    50: "hsl(var(--gray-true-50) / <alpha-value>)",
                    100: "hsl(var(--gray-true-100) / <alpha-value>)",
                    200: "hsl(var(--gray-true-200) / <alpha-value>)",
                    300: "hsl(var(--gray-true-300) / <alpha-value>)",
                    400: "hsl(var(--gray-true-400) / <alpha-value>)",
                    500: "hsl(var(--gray-true-500) / <alpha-value>)",
                    600: "hsl(var(--gray-true-600) / <alpha-value>)",
                    700: "hsl(var(--gray-true-700) / <alpha-value>)",
                    800: "hsl(var(--gray-true-800) / <alpha-value>)",
                    900: "hsl(var(--gray-true-900) / <alpha-value>)",
                    950: "hsl(var(--gray-true-950) / <alpha-value>)",
                },
                "gray-warm": {
                    25: "hsl(var(--gray-warm-25) / <alpha-value>)",
                    50: "hsl(var(--gray-warm-50) / <alpha-value>)",
                    100: "hsl(var(--gray-warm-100) / <alpha-value>)",
                    200: "hsl(var(--gray-warm-200) / <alpha-value>)",
                    300: "hsl(var(--gray-warm-300) / <alpha-value>)",
                    400: "hsl(var(--gray-warm-400) / <alpha-value>)",
                    500: "hsl(var(--gray-warm-500) / <alpha-value>)",
                    600: "hsl(var(--gray-warm-600) / <alpha-value>)",
                    700: "hsl(var(--gray-warm-700) / <alpha-value>)",
                    800: "hsl(var(--gray-warm-800) / <alpha-value>)",
                    900: "hsl(var(--gray-warm-900) / <alpha-value>)",
                    950: "hsl(var(--gray-warm-950) / <alpha-value>)",
                },
                moss: {
                    25: "hsl(var(--moss-25) / <alpha-value>)",
                    50: "hsl(var(--moss-50) / <alpha-value>)",
                    100: "hsl(var(--moss-100) / <alpha-value>)",
                    200: "hsl(var(--moss-200) / <alpha-value>)",
                    300: "hsl(var(--moss-300) / <alpha-value>)",
                    400: "hsl(var(--moss-400) / <alpha-value>)",
                    500: "hsl(var(--moss-500) / <alpha-value>)",
                    600: "hsl(var(--moss-600) / <alpha-value>)",
                    700: "hsl(var(--moss-700) / <alpha-value>)",
                    800: "hsl(var(--moss-800) / <alpha-value>)",
                    900: "hsl(var(--moss-900) / <alpha-value>)",
                    950: "hsl(var(--moss-950) / <alpha-value>)",
                },
                "green-light": {
                    25: "hsl(var(--green-light-25) / <alpha-value>)",
                    50: "hsl(var(--green-light-50) / <alpha-value>)",
                    100: "hsl(var(--green-light-100) / <alpha-value>)",
                    200: "hsl(var(--green-light-200) / <alpha-value>)",
                    300: "hsl(var(--green-light-300) / <alpha-value>)",
                    400: "hsl(var(--green-light-400) / <alpha-value>)",
                    500: "hsl(var(--green-light-500) / <alpha-value>)",
                    600: "hsl(var(--green-light-600) / <alpha-value>)",
                    700: "hsl(var(--green-light-700) / <alpha-value>)",
                    800: "hsl(var(--green-light-800) / <alpha-value>)",
                    900: "hsl(var(--green-light-900) / <alpha-value>)",
                    950: "hsl(var(--green-light-950) / <alpha-value>)",
                },
                green: {
                    25: "hsl(var(--green-25) / <alpha-value>)",
                    50: "hsl(var(--green-50) / <alpha-value>)",
                    100: "hsl(var(--green-100) / <alpha-value>)",
                    200: "hsl(var(--green-200) / <alpha-value>)",
                    300: "hsl(var(--green-300) / <alpha-value>)",
                    400: "hsl(var(--green-400) / <alpha-value>)",
                    500: "hsl(var(--green-500) / <alpha-value>)",
                    600: "hsl(var(--green-600) / <alpha-value>)",
                    700: "hsl(var(--green-700) / <alpha-value>)",
                    800: "hsl(var(--green-800) / <alpha-value>)",
                    900: "hsl(var(--green-900) / <alpha-value>)",
                    950: "hsl(var(--green-950) / <alpha-value>)",
                },
                teal: {
                    25: "hsl(var(--teal-25) / <alpha-value>)",
                    50: "hsl(var(--teal-50) / <alpha-value>)",
                    100: "hsl(var(--teal-100) / <alpha-value>)",
                    200: "hsl(var(--teal-200) / <alpha-value>)",
                    300: "hsl(var(--teal-300) / <alpha-value>)",
                    400: "hsl(var(--teal-400) / <alpha-value>)",
                    500: "hsl(var(--teal-500) / <alpha-value>)",
                    600: "hsl(var(--teal-600) / <alpha-value>)",
                    700: "hsl(var(--teal-700) / <alpha-value>)",
                    800: "hsl(var(--teal-800) / <alpha-value>)",
                    900: "hsl(var(--teal-900) / <alpha-value>)",
                    950: "hsl(var(--teal-950) / <alpha-value>)",
                },
                cyan: {
                    25: "hsl(var(--cyan-25) / <alpha-value>)",
                    50: "hsl(var(--cyan-50) / <alpha-value>)",
                    100: "hsl(var(--cyan-100) / <alpha-value>)",
                    200: "hsl(var(--cyan-200) / <alpha-value>)",
                    300: "hsl(var(--cyan-300) / <alpha-value>)",
                    400: "hsl(var(--cyan-400) / <alpha-value>)",
                    500: "hsl(var(--cyan-500) / <alpha-value>)",
                    600: "hsl(var(--cyan-600) / <alpha-value>)",
                    700: "hsl(var(--cyan-700) / <alpha-value>)",
                    800: "hsl(var(--cyan-800) / <alpha-value>)",
                    900: "hsl(var(--cyan-900) / <alpha-value>)",
                    950: "hsl(var(--cyan-950) / <alpha-value>)",
                },
                "blue-light": {
                    25: "hsl(var(--blue-light-25) / <alpha-value>)",
                    50: "hsl(var(--blue-light-50) / <alpha-value>)",
                    100: "hsl(var(--blue-light-100) / <alpha-value>)",
                    200: "hsl(var(--blue-light-200) / <alpha-value>)",
                    300: "hsl(var(--blue-light-300) / <alpha-value>)",
                    400: "hsl(var(--blue-light-400) / <alpha-value>)",
                    500: "hsl(var(--blue-light-500) / <alpha-value>)",
                    600: "hsl(var(--blue-light-600) / <alpha-value>)",
                    700: "hsl(var(--blue-light-700) / <alpha-value>)",
                    800: "hsl(var(--blue-light-800) / <alpha-value>)",
                    900: "hsl(var(--blue-light-900) / <alpha-value>)",
                    950: "hsl(var(--blue-light-950) / <alpha-value>)",
                },
                blue: {
                    25: "hsl(var(--blue-25) / <alpha-value>)",
                    50: "hsl(var(--blue-50) / <alpha-value>)",
                    100: "hsl(var(--blue-100) / <alpha-value>)",
                    200: "hsl(var(--blue-200) / <alpha-value>)",
                    300: "hsl(var(--blue-300) / <alpha-value>)",
                    400: "hsl(var(--blue-400) / <alpha-value>)",
                    500: "hsl(var(--blue-500) / <alpha-value>)",
                    600: "hsl(var(--blue-600) / <alpha-value>)",
                    700: "hsl(var(--blue-700) / <alpha-value>)",
                    800: "hsl(var(--blue-800) / <alpha-value>)",
                    900: "hsl(var(--blue-900) / <alpha-value>)",
                    950: "hsl(var(--blue-950) / <alpha-value>)",
                },
                "blue-dark": {
                    25: "hsl(var(--blue-dark-25) / <alpha-value>)",
                    50: "hsl(var(--blue-dark-50) / <alpha-value>)",
                    100: "hsl(var(--blue-dark-100) / <alpha-value>)",
                    200: "hsl(var(--blue-dark-200) / <alpha-value>)",
                    300: "hsl(var(--blue-dark-300) / <alpha-value>)",
                    400: "hsl(var(--blue-dark-400) / <alpha-value>)",
                    500: "hsl(var(--blue-dark-500) / <alpha-value>)",
                    600: "hsl(var(--blue-dark-600) / <alpha-value>)",
                    700: "hsl(var(--blue-dark-700) / <alpha-value>)",
                    800: "hsl(var(--blue-dark-800) / <alpha-value>)",
                    900: "hsl(var(--blue-dark-900) / <alpha-value>)",
                    950: "hsl(var(--blue-dark-950) / <alpha-value>)",
                },
                indigo: {
                    25: "hsl(var(--indigo-25) / <alpha-value>)",
                    50: "hsl(var(--indigo-50) / <alpha-value>)",
                    100: "hsl(var(--indigo-100) / <alpha-value>)",
                    200: "hsl(var(--indigo-200) / <alpha-value>)",
                    300: "hsl(var(--indigo-300) / <alpha-value>)",
                    400: "hsl(var(--indigo-400) / <alpha-value>)",
                    500: "hsl(var(--indigo-500) / <alpha-value>)",
                    600: "hsl(var(--indigo-600) / <alpha-value>)",
                    700: "hsl(var(--indigo-700) / <alpha-value>)",
                    800: "hsl(var(--indigo-800) / <alpha-value>)",
                    900: "hsl(var(--indigo-900) / <alpha-value>)",
                    950: "hsl(var(--indigo-950) / <alpha-value>)",
                },
                violet: {
                    25: "hsl(var(--violet-25) / <alpha-value>)",
                    50: "hsl(var(--violet-50) / <alpha-value>)",
                    100: "hsl(var(--violet-100) / <alpha-value>)",
                    200: "hsl(var(--violet-200) / <alpha-value>)",
                    300: "hsl(var(--violet-300) / <alpha-value>)",
                    400: "hsl(var(--violet-400) / <alpha-value>)",
                    500: "hsl(var(--violet-500) / <alpha-value>)",
                    600: "hsl(var(--violet-600) / <alpha-value>)",
                    700: "hsl(var(--violet-700) / <alpha-value>)",
                    800: "hsl(var(--violet-800) / <alpha-value>)",
                    900: "hsl(var(--violet-900) / <alpha-value>)",
                    950: "hsl(var(--violet-950) / <alpha-value>)",
                },
                purple: {
                    25: "hsl(var(--purple-25) / <alpha-value>)",
                    50: "hsl(var(--purple-50) / <alpha-value>)",
                    100: "hsl(var(--purple-100) / <alpha-value>)",
                    200: "hsl(var(--purple-200) / <alpha-value>)",
                    300: "hsl(var(--purple-300) / <alpha-value>)",
                    400: "hsl(var(--purple-400) / <alpha-value>)",
                    500: "hsl(var(--purple-500) / <alpha-value>)",
                    600: "hsl(var(--purple-600) / <alpha-value>)",
                    700: "hsl(var(--purple-700) / <alpha-value>)",
                    800: "hsl(var(--purple-800) / <alpha-value>)",
                    900: "hsl(var(--purple-900) / <alpha-value>)",
                    950: "hsl(var(--purple-950) / <alpha-value>)",
                },
                fuchsia: {
                    25: "hsl(var(--fuchsia-25) / <alpha-value>)",
                    50: "hsl(var(--fuchsia-50) / <alpha-value>)",
                    100: "hsl(var(--fuchsia-100) / <alpha-value>)",
                    200: "hsl(var(--fuchsia-200) / <alpha-value>)",
                    300: "hsl(var(--fuchsia-300) / <alpha-value>)",
                    400: "hsl(var(--fuchsia-400) / <alpha-value>)",
                    500: "hsl(var(--fuchsia-500) / <alpha-value>)",
                    600: "hsl(var(--fuchsia-600) / <alpha-value>)",
                    700: "hsl(var(--fuchsia-700) / <alpha-value>)",
                    800: "hsl(var(--fuchsia-800) / <alpha-value>)",
                    900: "hsl(var(--fuchsia-900) / <alpha-value>)",
                    950: "hsl(var(--fuchsia-950) / <alpha-value>)",
                },
                pink: {
                    25: "hsl(var(--pink-25) / <alpha-value>)",
                    50: "hsl(var(--pink-50) / <alpha-value>)",
                    100: "hsl(var(--pink-100) / <alpha-value>)",
                    200: "hsl(var(--pink-200) / <alpha-value>)",
                    300: "hsl(var(--pink-300) / <alpha-value>)",
                    400: "hsl(var(--pink-400) / <alpha-value>)",
                    500: "hsl(var(--pink-500) / <alpha-value>)",
                    600: "hsl(var(--pink-600) / <alpha-value>)",
                    700: "hsl(var(--pink-700) / <alpha-value>)",
                    800: "hsl(var(--pink-800) / <alpha-value>)",
                    900: "hsl(var(--pink-900) / <alpha-value>)",
                    950: "hsl(var(--pink-950) / <alpha-value>)",
                },
                rose: {
                    25: "hsl(var(--rose-25) / <alpha-value>)",
                    50: "hsl(var(--rose-50) / <alpha-value>)",
                    100: "hsl(var(--rose-100) / <alpha-value>)",
                    200: "hsl(var(--rose-200) / <alpha-value>)",
                    300: "hsl(var(--rose-300) / <alpha-value>)",
                    400: "hsl(var(--rose-400) / <alpha-value>)",
                    500: "hsl(var(--rose-500) / <alpha-value>)",
                    600: "hsl(var(--rose-600) / <alpha-value>)",
                    700: "hsl(var(--rose-700) / <alpha-value>)",
                    800: "hsl(var(--rose-800) / <alpha-value>)",
                    900: "hsl(var(--rose-900) / <alpha-value>)",
                    950: "hsl(var(--rose-950) / <alpha-value>)",
                },
                orange: {
                    25: "hsl(var(--orange-25) / <alpha-value>)",
                    50: "hsl(var(--orange-50) / <alpha-value>)",
                    100: "hsl(var(--orange-100) / <alpha-value>)",
                    200: "hsl(var(--orange-200) / <alpha-value>)",
                    300: "hsl(var(--orange-300) / <alpha-value>)",
                    400: "hsl(var(--orange-400) / <alpha-value>)",
                    500: "hsl(var(--orange-500) / <alpha-value>)",
                    600: "hsl(var(--orange-600) / <alpha-value>)",
                    700: "hsl(var(--orange-700) / <alpha-value>)",
                    800: "hsl(var(--orange-800) / <alpha-value>)",
                    900: "hsl(var(--orange-900) / <alpha-value>)",
                    950: "hsl(var(--orange-950) / <alpha-value>)",
                },
                "orange-dark": {
                    25: "hsl(var(--orange-dark-25) / <alpha-value>)",
                    50: "hsl(var(--orange-dark-50) / <alpha-value>)",
                    100: "hsl(var(--orange-dark-100) / <alpha-value>)",
                    200: "hsl(var(--orange-dark-200) / <alpha-value>)",
                    300: "hsl(var(--orange-dark-300) / <alpha-value>)",
                    400: "hsl(var(--orange-dark-400) / <alpha-value>)",
                    500: "hsl(var(--orange-dark-500) / <alpha-value>)",
                    600: "hsl(var(--orange-dark-600) / <alpha-value>)",
                    700: "hsl(var(--orange-dark-700) / <alpha-value>)",
                    800: "hsl(var(--orange-dark-800) / <alpha-value>)",
                    900: "hsl(var(--orange-dark-900) / <alpha-value>)",
                    950: "hsl(var(--orange-dark-950) / <alpha-value>)",
                },
                yellow: {
                    25: "hsl(var(--yellow-25) / <alpha-value>)",
                    50: "hsl(var(--yellow-50) / <alpha-value>)",
                    100: "hsl(var(--yellow-100) / <alpha-value>)",
                    200: "hsl(var(--yellow-200) / <alpha-value>)",
                    300: "hsl(var(--yellow-300) / <alpha-value>)",
                    400: "hsl(var(--yellow-400) / <alpha-value>)",
                    500: "hsl(var(--yellow-500) / <alpha-value>)",
                    600: "hsl(var(--yellow-600) / <alpha-value>)",
                    700: "hsl(var(--yellow-700) / <alpha-value>)",
                    800: "hsl(var(--yellow-800) / <alpha-value>)",
                    900: "hsl(var(--yellow-900) / <alpha-value>)",
                    950: "hsl(var(--yellow-950) / <alpha-value>)",
                },
                utility: {
                    gray: {
                        50: "hsl(var(--utility-gray-50) / <alpha-value>)",
                        100: "hsl(var(--utility-gray-100) / <alpha-value>)",
                        200: "hsl(var(--utility-gray-200) / <alpha-value>)",
                        300: "hsl(var(--utility-gray-300) / <alpha-value>)",
                        400: "hsl(var(--utility-gray-400) / <alpha-value>)",
                        500: "hsl(var(--utility-gray-500) / <alpha-value>)",
                        600: "hsl(var(--utility-gray-600) / <alpha-value>)",
                        700: "hsl(var(--utility-gray-700) / <alpha-value>)",
                        800: "hsl(var(--utility-gray-800) / <alpha-value>)",
                        900: "hsl(var(--utility-gray-900) / <alpha-value>)",
                    },
                    brand: {
                        50: "hsl(var(--utility-brand-50) / <alpha-value>)",
                        "50-alt": "hsl(var(--utility-brand-50-alt) / <alpha-value>)",
                        100: "hsl(var(--utility-brand-100) / <alpha-value>)",
                        "100-alt": "hsl(var(--utility-brand-100-alt) / <alpha-value>)",
                        200: "hsl(var(--utility-brand-200) / <alpha-value>)",
                        "200-alt": "hsl(var(--utility-brand-200-alt) / <alpha-value>)",
                        300: "hsl(var(--utility-brand-300) / <alpha-value>)",
                        "300-alt": "hsl(var(--utility-brand-300-alt) / <alpha-value>)",
                        400: "hsl(var(--utility-brand-400) / <alpha-value>)",
                        "400-alt": "hsl(var(--utility-brand-400-alt) / <alpha-value>)",
                        500: "hsl(var(--utility-brand-500) / <alpha-value>)",
                        "500-alt": "hsl(var(--utility-brand-500-alt) / <alpha-value>)",
                        600: "hsl(var(--utility-brand-600) / <alpha-value>)",
                        "600-alt": "hsl(var(--utility-brand-600-alt) / <alpha-value>)",
                        700: "hsl(var(--utility-brand-700) / <alpha-value>)",
                        "700-alt": "hsl(var(--utility-brand-700-alt) / <alpha-value>)",
                        800: "hsl(var(--utility-brand-800) / <alpha-value>)",
                        "800-alt": "hsl(var(--utility-brand-800-alt) / <alpha-value>)",
                        900: "hsl(var(--utility-brand-900) / <alpha-value>)",
                        "900-alt": "hsl(var(--utility-brand-900-alt) / <alpha-value>)",
                    },
                    error: {
                        50: "hsl(var(--utility-error-50) / <alpha-value>)",
                        100: "hsl(var(--utility-error-100) / <alpha-value>)",
                        200: "hsl(var(--utility-error-200) / <alpha-value>)",
                        300: "hsl(var(--utility-error-300) / <alpha-value>)",
                        400: "hsl(var(--utility-error-400) / <alpha-value>)",
                        500: "hsl(var(--utility-error-500) / <alpha-value>)",
                        600: "hsl(var(--utility-error-600) / <alpha-value>)",
                        700: "hsl(var(--utility-error-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-error-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-error-900) / <alpha-value>)",
                    },
                    warning: {
                        50: "hsl(var(--utility-warning-50) / <alpha-value>)",
                        100: "hsl(var(--utility-warning-100) / <alpha-value>)",
                        200: "hsl(var(--utility-warning-200) / <alpha-value>)",
                        300: "hsl(var(--utility-warning-300) / <alpha-value>)",
                        400: "hsl(var(--utility-warning-400) / <alpha-value>)",
                        500: "hsl(var(--utility-warning-500) / <alpha-value>)",
                        600: "hsl(var(--utility-warning-600) / <alpha-value>)",
                        700: "hsl(var(--utility-warning-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-warning-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-warning-900) / <alpha-value>)",
                    },
                    success: {
                        50: "hsl(var(--utility-success-50) / <alpha-value>)",
                        100: "hsl(var(--utility-success-100) / <alpha-value>)",
                        200: "hsl(var(--utility-success-200) / <alpha-value>)",
                        300: "hsl(var(--utility-success-300) / <alpha-value>)",
                        400: "hsl(var(--utility-success-400) / <alpha-value>)",
                        500: "hsl(var(--utility-success-500) / <alpha-value>)",
                        600: "hsl(var(--utility-success-600) / <alpha-value>)",
                        700: "hsl(var(--utility-success-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-success-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-success-900) / <alpha-value>)",
                    },
                    info: {
                        50: "hsl(var(--utility-info-50) / <alpha-value>)",
                        100: "hsl(var(--utility-info-100) / <alpha-value>)",
                        200: "hsl(var(--utility-info-200) / <alpha-value>)",
                        300: "hsl(var(--utility-info-300) / <alpha-value>)",
                        400: "hsl(var(--utility-info-400) / <alpha-value>)",
                        500: "hsl(var(--utility-info-500) / <alpha-value>)",
                        600: "hsl(var(--utility-info-600) / <alpha-value>)",
                        700: "hsl(var(--utility-info-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-info-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-info-900) / <alpha-value>)",
                    },
                    help: {
                        50: "hsl(var(--utility-help-50) / <alpha-value>)",
                        100: "hsl(var(--utility-help-100) / <alpha-value>)",
                        200: "hsl(var(--utility-help-200) / <alpha-value>)",
                        300: "hsl(var(--utility-help-300) / <alpha-value>)",
                        400: "hsl(var(--utility-help-400) / <alpha-value>)",
                        500: "hsl(var(--utility-help-500) / <alpha-value>)",
                        600: "hsl(var(--utility-help-600) / <alpha-value>)",
                        700: "hsl(var(--utility-help-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-help-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-help-900) / <alpha-value>)",
                    },
                    "gray-blue": {
                        50: "hsl(var(--utility-gray-blue-50) / <alpha-value>)",
                        100: "hsl(var(--utility-gray-blue-100) / <alpha-value>)",
                        200: "hsl(var(--utility-gray-blue-200) / <alpha-value>)",
                        300: "hsl(var(--utility-gray-blue-300) / <alpha-value>)",
                        400: "hsl(var(--utility-gray-blue-400) / <alpha-value>)",
                        500: "hsl(var(--utility-gray-blue-500) / <alpha-value>)",
                        600: "hsl(var(--utility-gray-blue-600) / <alpha-value>)",
                        700: "hsl(var(--utility-gray-blue-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-gray-blue-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-gray-blue-900) / <alpha-value>)",
                    },
                    "blue-light": {
                        50: "hsl(var(--utility-blue-light-50) / <alpha-value>)",
                        100: "hsl(var(--utility-blue-light-100) / <alpha-value>)",
                        200: "hsl(var(--utility-blue-light-200) / <alpha-value>)",
                        300: "hsl(var(--utility-blue-light-300) / <alpha-value>)",
                        400: "hsl(var(--utility-blue-light-400) / <alpha-value>)",
                        500: "hsl(var(--utility-blue-light-500) / <alpha-value>)",
                        600: "hsl(var(--utility-blue-light-600) / <alpha-value>)",
                        700: "hsl(var(--utility-blue-light-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-blue-light-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-blue-light-900) / <alpha-value>)",
                    },
                    blue: {
                        50: "hsl(var(--utility-blue-50) / <alpha-value>)",
                        100: "hsl(var(--utility-blue-100) / <alpha-value>)",
                        200: "hsl(var(--utility-blue-200) / <alpha-value>)",
                        300: "hsl(var(--utility-blue-300) / <alpha-value>)",
                        400: "hsl(var(--utility-blue-400) / <alpha-value>)",
                        500: "hsl(var(--utility-blue-500) / <alpha-value>)",
                        600: "hsl(var(--utility-blue-600) / <alpha-value>)",
                        700: "hsl(var(--utility-blue-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-blue-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-blue-900) / <alpha-value>)",
                    },
                    "blue-dark": {
                        50: "hsl(var(--utility-blue-dark-50) / <alpha-value>)",
                        100: "hsl(var(--utility-blue-dark-100) / <alpha-value>)",
                        200: "hsl(var(--utility-blue-dark-200) / <alpha-value>)",
                        300: "hsl(var(--utility-blue-dark-300) / <alpha-value>)",
                        400: "hsl(var(--utility-blue-dark-400) / <alpha-value>)",
                        500: "hsl(var(--utility-blue-dark-500) / <alpha-value>)",
                        600: "hsl(var(--utility-blue-dark-600) / <alpha-value>)",
                        700: "hsl(var(--utility-blue-dark-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-blue-dark-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-blue-dark-900) / <alpha-value>)",
                    },
                    indigo: {
                        50: "hsl(var(--utility-indigo-50) / <alpha-value>)",
                        100: "hsl(var(--utility-indigo-100) / <alpha-value>)",
                        200: "hsl(var(--utility-indigo-200) / <alpha-value>)",
                        300: "hsl(var(--utility-indigo-300) / <alpha-value>)",
                        400: "hsl(var(--utility-indigo-400) / <alpha-value>)",
                        500: "hsl(var(--utility-indigo-500) / <alpha-value>)",
                        600: "hsl(var(--utility-indigo-600) / <alpha-value>)",
                        700: "hsl(var(--utility-indigo-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-indigo-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-indigo-900) / <alpha-value>)",
                    },
                    purple: {
                        50: "hsl(var(--utility-purple-50) / <alpha-value>)",
                        100: "hsl(var(--utility-purple-100) / <alpha-value>)",
                        200: "hsl(var(--utility-purple-200) / <alpha-value>)",
                        300: "hsl(var(--utility-purple-300) / <alpha-value>)",
                        400: "hsl(var(--utility-purple-400) / <alpha-value>)",
                        500: "hsl(var(--utility-purple-500) / <alpha-value>)",
                        600: "hsl(var(--utility-purple-600) / <alpha-value>)",
                        700: "hsl(var(--utility-purple-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-purple-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-purple-900) / <alpha-value>)",
                    },
                    fuchsia: {
                        50: "hsl(var(--utility-fuchsia-50) / <alpha-value>)",
                        100: "hsl(var(--utility-fuchsia-100) / <alpha-value>)",
                        200: "hsl(var(--utility-fuchsia-200) / <alpha-value>)",
                        300: "hsl(var(--utility-fuchsia-300) / <alpha-value>)",
                        400: "hsl(var(--utility-fuchsia-400) / <alpha-value>)",
                        500: "hsl(var(--utility-fuchsia-500) / <alpha-value>)",
                        600: "hsl(var(--utility-fuchsia-600) / <alpha-value>)",
                        700: "hsl(var(--utility-fuchsia-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-fuchsia-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-fuchsia-900) / <alpha-value>)",
                    },
                    pink: {
                        50: "hsl(var(--utility-pink-50) / <alpha-value>)",
                        100: "hsl(var(--utility-pink-100) / <alpha-value>)",
                        200: "hsl(var(--utility-pink-200) / <alpha-value>)",
                        300: "hsl(var(--utility-pink-300) / <alpha-value>)",
                        400: "hsl(var(--utility-pink-400) / <alpha-value>)",
                        500: "hsl(var(--utility-pink-500) / <alpha-value>)",
                        600: "hsl(var(--utility-pink-600) / <alpha-value>)",
                        700: "hsl(var(--utility-pink-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-pink-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-pink-900) / <alpha-value>)",
                    },
                    orange: {
                        50: "hsl(var(--utility-orange-50) / <alpha-value>)",
                        100: "hsl(var(--utility-orange-100) / <alpha-value>)",
                        200: "hsl(var(--utility-orange-200) / <alpha-value>)",
                        300: "hsl(var(--utility-orange-300) / <alpha-value>)",
                        400: "hsl(var(--utility-orange-400) / <alpha-value>)",
                        500: "hsl(var(--utility-orange-500) / <alpha-value>)",
                        600: "hsl(var(--utility-orange-600) / <alpha-value>)",
                        700: "hsl(var(--utility-orange-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-orange-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-orange-900) / <alpha-value>)",
                    },
                    "orange-dark": {
                        50: "hsl(var(--utility-orange-dark-50) / <alpha-value>)",
                        100: "hsl(var(--utility-orange-dark-100) / <alpha-value>)",
                        200: "hsl(var(--utility-orange-dark-200) / <alpha-value>)",
                        300: "hsl(var(--utility-orange-dark-300) / <alpha-value>)",
                        400: "hsl(var(--utility-orange-dark-400) / <alpha-value>)",
                        500: "hsl(var(--utility-orange-dark-500) / <alpha-value>)",
                        600: "hsl(var(--utility-orange-dark-600) / <alpha-value>)",
                        700: "hsl(var(--utility-orange-dark-700) / <alpha-value>)",
                        // 800: "hsl(var(--utility-orange-dark-800) / <alpha-value>)",
                        // 900: "hsl(var(--utility-orange-dark-900) / <alpha-value>)",
                    },
                },
                text: {
                    primary: {
                        DEFAULT: "hsl(var(--text-primary) / <alpha-value>)",
                        "on-brand": "hsl(var(--text-primary-on-brand) / <alpha-value>)",
                    },
                    secondary: {
                        DEFAULT: "hsl(var(--text-secondary) / <alpha-value>)",
                        hover: "hsl(var(--text-secondary-hover) / <alpha-value>)",
                        "on-brand": "hsl(var(--text-secondary-on-brand) / <alpha-value>)",
                    },
                    tertiary: {
                        DEFAULT: "hsl(var(--text-tertiary) / <alpha-value>)",
                        hover: "hsl(var(--text-tertiary-hover) / <alpha-value>)",
                        "on-brand": "hsl(var(--text-tertiary-on-brand) / <alpha-value>)",
                    },
                    quaternary: {
                        DEFAULT: "hsl(var(--text-quaternary) / <alpha-value>)",
                        "on-brand": "hsl(var(--text-quaternary-on-brand) / <alpha-value>)",
                    },
                    white: "hsl(var(--text-white) / <alpha-value>)",
                    disabled: "hsl(var(--text-disabled) / <alpha-value>)",
                    placeholder: {
                        DEFAULT: "hsl(var(--text-placeholder) / <alpha-value>)",
                        subtle: "hsl(var(--text-placeholder-subtle) / <alpha-value>)",
                    },
                    brand: {
                        primary: "hsl(var(--text-brand-primary) / <alpha-value>)",
                        secondary: "hsl(var(--text-brand-secondary) / <alpha-value>)",
                        tertiary: {
                            DEFAULT: "hsl(var(--text-brand-tertiary) / <alpha-value>)",
                            alt: "hsl(var(--text-brand-tertiary-alt) / <alpha-value>)",
                        },
                    },
                    error: {
                        primary: "hsl(var(--text-error-primary) / <alpha-value>)",
                    },
                    warning: {
                        primary: "hsl(var(--text-warning-primary) / <alpha-value>)",
                    },
                    success: {
                        primary: "hsl(var(--text-success-primary) / <alpha-value>)",
                    },
                },

                border: {
                    primary: "hsl(var(--border-primary) / <alpha-value>)",
                    secondary: "hsl(var(--border-secondary) / <alpha-value>)",
                    tertiary: "hsl(var(--border-tertiary) / <alpha-value>)",
                    disabled: {
                        DEFAULT: "hsl(var(--border-disabled) / <alpha-value>)",
                        subtle: "hsl(var(--border-disabled-subtle) / <alpha-value>)",
                    },
                    brand: {
                        DEFAULT: "hsl(var(--border-brand) / <alpha-value>)",
                        solid: {
                            DEFAULT: "hsl(var(--border-brand-solid) / <alpha-value>)",
                            alt: "hsl(var(--border-brand-solid-alt) / <alpha-value>)",
                        },
                    },
                    error: {
                        DEFAULT: "hsl(var(--border-error) / <alpha-value>)",
                        solid: "hsl(var(--border-error-solid) / <alpha-value>)",
                    },
                },

                ring: {
                    primary: "hsl(var(--ring-primary) / 0.24)",
                    brand: "hsl(var(--ring-brand) / 0.24)",
                    error: "hsl(var(--ring-error) / 0.24)",
                    warning: "hsl(var(--ring-warning) / 0.24)",
                    success: "hsl(var(--ring-success) / 0.24)",
                    info: "hsl(var(--ring-info) / 0.24)",
                    help: "hsl(var(--ring-help) / 0.24)",
                },

                foreground: {
                    primary: "hsl(var(--foreground-primary) / <alpha-value>)",
                    secondary: {
                        DEFAULT: "hsl(var(--foreground-secondary) / <alpha-value>)",
                        hover: "hsl(var(--foreground-secondary-hover) / <alpha-value>)",
                    },
                    tertiary: {
                        DEFAULT: "hsl(var(--foreground-tertiary) / <alpha-value>)",
                        hover: "hsl(var(--foreground-tertiary-hover) / <alpha-value>)",
                    },
                    quaternary: {
                        DEFAULT: "hsl(var(--foreground-quaternary) / <alpha-value>)",
                        hover: "hsl(var(--foreground-quaternary-hover) / <alpha-value>)",
                    },
                    quinary: {
                        DEFAULT: "hsl(var(--foreground-quinary) / <alpha-value>)",
                        hover: "hsl(var(--foreground-quinary-hover) / <alpha-value>)",
                    },
                    senary: "hsl(var(--foreground-senary) / <alpha-value>)",
                    white: "hsl(var(--foreground-white) / <alpha-value>)",
                    disabled: {
                        DEFAULT: "hsl(var(--foreground-disabled) / <alpha-value>)",
                        subtle: "hsl(var(--foreground-disabled-subtle) / <alpha-value>)",
                    },

                    brand: {
                        primary: {
                            DEFAULT: "hsl(var(--foreground-brand-primary) / <alpha-value>)",
                            alt: "hsl(var(--foreground-brand-primary-alt) / <alpha-value>)",
                        },
                        secondary: "hsl(var(--foreground-brand-secondary) / <alpha-value>)",
                    },
                    error: {
                        primary: "hsl(var(--foreground-error-primary) / <alpha-value>)",
                        secondary: "hsl(var(--foreground-error-secondary) / <alpha-value>)",
                    },
                    warning: {
                        primary: "hsl(var(--foreground-warning-primary) / <alpha-value>)",
                        secondary: "hsl(var(--foreground-warning-secondary) / <alpha-value>)",
                    },
                    success: {
                        primary: "hsl(var(--foreground-success-primary) / <alpha-value>)",
                        secondary: "hsl(var(--foreground-success-secondary) / <alpha-value>)",
                    },
                    info: {
                        primary: "hsl(var(--foreground-info-primary) / <alpha-value>)",
                        secondary: "hsl(var(--foreground-info-secondary) / <alpha-value>)",
                    },
                    help: {
                        primary: "hsl(var(--foreground-help-primary) / <alpha-value>)",
                        secondary: "hsl(var(--foreground-help-secondary) / <alpha-value>)",
                    },
                },

                background: {
                    primary: {
                        DEFAULT: "hsl(var(--background-primary) / <alpha-value>)",
                        alt: "hsl(var(--background-primary-alt) / <alpha-value>)",
                        hover: "hsl(var(--background-primary-hover) / <alpha-value>)",
                        solid: "hsl(var(--background-primary-solid) / <alpha-value>)",
                    },
                    secondary: {
                        DEFAULT: "hsl(var(--background-secondary) / <alpha-value>)",
                        alt: "hsl(var(--background-secondary-alt) / <alpha-value>)",
                        hover: "hsl(var(--background-secondary-hover) / <alpha-value>)",
                        solid: "hsl(var(--background-secondary-solid) / <alpha-value>)",
                    },
                    tertiary: "hsl(var(--background-tertiary) / <alpha-value>)",
                    quaternary: "hsl(var(--background-quaternary) / <alpha-value>)",
                    active: "hsl(var(--background-active) / <alpha-value>)",
                    disabled: {
                        DEFAULT: "hsl(var(--background-disabled) / <alpha-value>)",
                        subtle: "hsl(var(--background-disabled-subtle) / <alpha-value>)",
                    },
                    // overlay: "hsl(var(--background-overlay) / <alpha-value>)",
                    overlay: {
                        DEFAULT: "hsl(var(--background-overlay) / <alpha-value>)",
                        alt: "hsl(var(--background-overlay) / .75)",
                    },
                    brand: {
                        primary: {
                            DEFAULT: "hsl(var(--background-brand-primary) / <alpha-value>)",
                            alt: "hsl(var(--background-brand-primary-alt) / <alpha-value>)",
                        },
                        secondary: "hsl(var(--background-brand-secondary) / <alpha-value>)",
                        solid: {
                            DEFAULT: "hsl(var(--background-brand-solid) / <alpha-value>)",
                            hover: "hsl(var(--background-brand-solid-hover) / <alpha-value>)",
                        },
                    },
                    error: {
                        primary: "hsl(var(--background-error-primary) / <alpha-value>)",
                        secondary: "hsl(var(--background-error-secondary) / <alpha-value>)",
                        solid: "hsl(var(--background-error-solid) / <alpha-value>)",
                    },
                    warning: {
                        primary: "hsl(var(--background-warning-primary) / <alpha-value>)",
                        secondary: "hsl(var(--background-warning-secondary) / <alpha-value>)",
                        solid: "hsl(var(--background-warning-solid) / <alpha-value>)",
                    },
                    success: {
                        primary: "hsl(var(--background-success-primary) / <alpha-value>)",
                        secondary: "hsl(var(--background-success-secondary) / <alpha-value>)",
                        solid: "hsl(var(--background-success-solid) / <alpha-value>)",
                    },
                    info: {
                        primary: "hsl(var(--background-info-primary) / <alpha-value>)",
                        secondary: "hsl(var(--background-info-secondary) / <alpha-value>)",
                        solid: "hsl(var(--background-info-solid) / <alpha-value>)",
                    },
                    help: {
                        primary: "hsl(var(--background-help-primary) / <alpha-value>)",
                        secondary: "hsl(var(--background-help-secondary) / <alpha-value>)",
                        solid: "hsl(var(--background-help-solid) / <alpha-value>)",
                    },
                },
            },
            borderRadius: {
                xs: "calc(var(--radius) - 6px)",
                "xs-inset": "calc(var(--radius) - 7px)",
                sm: "calc(var(--radius) - 4px)",
                "sm-inset": "calc(var(--radius) - 5px)",
                md: "calc(var(--radius) - 2px)",
                "md-inset": "calc(var(--radius) - 3px)",
                lg: "var(--radius)",
                "lg-inset": "calc(var(--radius) - 1px)",
                xl: "calc(var(--radius) + 2px)",
                "xl-inset": "calc(var(--radius) + 1px)",
                "2xl": "calc(var(--radius) + 4px)",
                "2xl-inset": "calc(var(--radius) + 3px)",
            },
            aria: {
                invalid: "invalid=\"true\"",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
                "collapsible-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-collapsible-content-height)" },
                },
                "collapsible-up": {
                    from: { height: "var(--radix-collapsible-content-height)" },
                    to: { height: 0 },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "collapsible-down": "collapsible-down 0.2s ease-in-out",
                "collapsible-up": "collapsible-up 0.2s ease-in-out",
            },
        },
    },

    plugins: [
        animate,
        plugin(function ({ matchUtilities, theme }) {
            matchUtilities(
                {
                    mask: value => ({
                        "mask-image": value,
                    }),
                },
                { values: theme("maskImage") },
            );
        }),
        plugin(function ({ matchUtilities, theme }) {
            matchUtilities(
                {
                    mask: value => ({
                        "mask-mode": value,
                    }),
                },
                { values: theme("maskMode") },
            );
        }),
    ],
};
